version: '3'
services:
  # application:
    # image:
    # container_name:
    # volumes:
    # ports:
    #   - "8080:80"
    # depends_on:
    #   - mysqldb
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    command: mysqld --user=root --verbose
    volumes:
       - ./UfoHotspots.sql:/docker-entrypoint-initdb.d/UfoHotspots.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"